### get all posts:
GET http://localhost:8080/api/v1/posts



### add a post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA 1",
  "description": "@Min @Max Annotation 1",
  "content": "Some Annotations 1"
}


### add a post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA 2",
  "description": "@Min @Max Annotation 2",
  "content": "Some Annotations 2"
}


### add a post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA 3",
  "description": "@Min @Max Annotation 3",
  "content": "Some Annotations 3"
}

### add a post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA 4",
  "description": "@Min @Max Annotation 4",
  "content": "Some Annotations 4"
}


### add a post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA 5",
  "description": "@Min @Max Annotation 5",
  "content": "Some Annotations 5"
}


### get post by id:
GET http://localhost:8080/api/v1/posts/1


### get post by invalid id:
GET http://localhost:8080/api/v1/posts/2

### update post by id:
PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json

{
  "title": "Learn Spring Data JPA!",
  "description": "@Min @Max Annotation!",
  "content": "Some Annotations!"
}

### update post without id:
PUT http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Learn Spring Data JPA!",
  "description": "@Min @Max Annotation!",
  "content": "Some Annotations!"
}

### update post with invalid id:
PUT http://localhost:8080/api/v1/posts/3
Content-Type: application/json

{
  "title": "Learn Spring Data JPA!",
  "description": "@Min @Max Annotation!",
  "content": "Some Annotations!"
}

### Delete post by id:
DELETE http://localhost:8080/api/v1/posts/1


### Delete post by invalid id:
DELETE http://localhost:8080/api/v1/posts/3


### get post page:
GET http://localhost:8080/api/v1/posts/page?pageSize=2&pageNo=1&sortBy=title&sortDir=desc